# Generated by Django 5.2 on 2025-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudAPI', '0002_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='vm_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
