# Generated by Django 5.2 on 2025-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudAPI', '0003_virtualmachine_vm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
