# Generated by Django 5.2 on 2025-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudAPI', '0004_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_off',
            field=models.DateTimeField(null=True),
        ),
    ]
